events {}

http {
  server {
    listen 8443 ssl;
    server_name localhost;

    ssl_certificate test/cert.pem;
    ssl_certificate_key test/key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
      root html;
      index index.html index.htm;
    }
  }
}
